# Generated by Django 5.0.2 on 2024-02-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Сomment', '0002_alter_post_id_alter_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='home_page',
        ),
    ]
